### ISSUE TITLE
ERROR -- : could not obtain a database connection within 5.000 seconds (waited 5.000 seconds) (ActiveRecord::ConnectionTimeoutError)

### ISSUE THREAD

**Issue by davidjuin0519** [boazsegev/plezi#15] opened 2016-01-30 16:02 UTC
I really appreciate your kind and detailed response to all my reported issue since recently I am trying to utilize Plezi to create some websocket application.

Whenever I refresh the page more than twice, the server crashes and with this error message:

```
ERROR -- : could not obtain a database connection within 5.000 seconds (waited 5.000 seconds) (ActiveRecord::ConnectionTimeoutError)
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:189:in `block in wait_poll'
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `loop'
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `wait_poll'
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:135:in `block in poll'
/Users/davidjuin0519/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:145:in `synchronize'
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:133:in `poll'
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:425:in `acquire_connection'
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/Users/davidjuin0519/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/Users/davidjuin0519/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/Users/davidjuin0519/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:87:in `connection'
```

I am sure that the websocket connection is closed and the controller `on_close` action is triggered...
I wonder what causes the server to crash and how to fix it...

**Comment by boazsegev** [comment] 2016-01-30 16:26
The issue is with multi-threading, Rails and ActiveRecord.

When using multi-threading, you need enough database connections for each thread you're using.

Plezi (through Iodine) is using a thread pool.

Assuming you're using the default amount of threads in your thread pool (you can set the the thread pool to 1, if you want a single worker thread), you're using ~30 threads in your thread-pool.

This means you need (at least) 30 connections in your database connection pool.

You can control this by editing the number of connections in your `config/database.yml` file:
```yaml
default: &default
  pool: 40
  timeout: 5000
```

When using Rails with servers that support multi-threaded concurrency (i.e. [Puma and Iodine, passenger](http://stackoverflow.com/questions/17902386/is-puma-the-only-multi-threaded-rails-4-http-server)), it's important to be aware of some potential related issues that could occur.

i.e., the following articles explain more:

* [Multithreading and Rails 4](http://cb.platan.us/multithreading-rails-4)

* [Make Your Rails Application Multi-Threaded on Heroku](http://blog.craz8.com/articles/2013/6/19/make-your-rails-application-multi-threaded)

* [ActiveRecord Concurrency in Rails4: Avoid leaked connections](https://bibwild.wordpress.com/2014/07/17/activerecord-concurrency-in-rails4-avoid-leaked-connections/)

* [Deploying Rails Applications with the Puma Web Server](https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server) (similar issues and solutions, but you will need to tweak the code and adjust it.

**Comment by davidjuin0519** [comment] 2016-02-04 03:24
Hi Bo, 
Thank you for revealing these resources.
I just wonder: how can I scale up websocket application? And what is the good design of scalable architecture?

(Perhaps this question is not supposed to be in issue...)

**Comment by boazsegev** [comment] 2016-08-05 06:46
I'm closing this, as the next release (coming soon) is a total rewrite, for Plezi as well as Iodine.

If the new version (v. 0.14.0, unreleased just yet) invokes similar (or new) issues, please open a new issue and let me know.

Thanks.

**Closed by boazsegev** 2016-08-05 06:46 UTC
Labels: question

**Comment by dccmmtop** [comment] 2017-09-29 08:36
how to close the connection?? I dont kown.. hlep me

**Comment by boazsegev** [comment] 2017-09-29 12:07
@dccmmtop ,

Thank you for posting your question.

However, I'm not sure this topic is the correct place - is your question related to this topic?

Are you asking how to close a database connection? Or are you asking how to close a Websocket connection?

### Database Connections

If you're using ActiveRecord, you can use `ActiveRecord::Base.remove_connection` to close the database connections inn the pool.

Remember to call `ActiveRecord::Base.establish_connection` before trying to access the database.

See [this SO question](https://stackoverflow.com/questions/45174080/lost-connection-to-mysql-server-during-query-on-random-simple-queries/45570999#45570999) regarding `fork`ing and database connection establishment.

If you are using `sequel`, use the `disconnect` method, as described [here](https://stackoverflow.com/questions/2783359/how-to-disconnect-an-existing-ruby-sequel-connection-to-a-database). I'm not sure if reconnection is automatic or a new connection object should be created.

### Websocket connection

Plezi controllers inherit from [`Iodine::Websocket`](http://www.rubydoc.info/github/boazsegev/iodine/master/Iodine/Websocket).

Simply call the [`Controller#close` method](http://www.rubydoc.info/github/boazsegev/iodine/master/Iodine/Websocket#close-instance_method) to close a Websocket connection.

P.S.

You can always ask any questions you have about specific code in the [StackOverflow](https://stackoverflow.com) website. This way, you might get a faster answer and more people can help you.

You can mention me in a comment (my handle is [@myst](https://stackoverflow.com/users/4025095/myst)) if you want my attention in SO.

Kindly,
   B.
